### ISSUE TITLE
upstart provider returning before service actually available on :restart and :reload actions

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/mysql#280]
This causes timing errors on replication-test suites on fast machines.

**Comment by someara** [comment]
FIxed in 6.0.7

**Comment by JAG-01** [comment]
Hello, I believe I may have a related issue with 6.0.7 upon initial deploy getting the following error or the start portion of the upstart restart. Thanks for the help and my apologies if this is not a related issue.

```ruby
# Attributes file
default[:app][:name] = "myappname"

# Recipe file
mysql_service "#{node[:app][:name]}" do
  version "5.6"
  initial_root_password "#{node[:app][:name]}123"
  action [:create, :start]
end

mysql_config "#{node[:app][:name]}" do
  instance "#{node[:app][:name]}"
  source "#{node[:app][:name]}.cnf.erb"
  owner "mysql"
  group "mysql"
  variables(
    :app_name => node[:app][:name],
    :config_dir => "/etc/mysql-#{node[:app][:name]}/conf.d",
    :cookbook_name => cookbook_name,
    :data_dir => "/var/lib/mysql-#{node[:app][:name]}",
    :log_dir => "#{node[:app][:deploy_to]}/shared/log",
    :pid_dir => "#{node[:app][:deploy_to]}/shared/pids"
  )
  action :create
  notifies :restart, "mysql_service[myappname]"
end

# Template file
# Generated by Chef for <%= node[:hostname] %>
# Controlling Cookbook: <%= @cookbook_name %>
#
# <%= @config_dir %>/<%= @app_name %>.cnf

[client]
default-character-set   = utf8
port                    = 3306
socket                  = <%= @pid_dir %>/mysqld.sock

[mysql]
default-character-set   = utf8

[mysqld]
user                    = mysql
pid-file                = <%= @pid_dir %>/mysqld.pid
socket                  = <%= @pid_dir %>/mysqld.sock
port                    = 3306
#basedir                 = /usr
datadir                 = <%= @data_dir %>
tmpdir                  = /tmp
lc-messages-dir         = /usr/share/mysql
max_allowed_packet      = 10485760
max_connections         = 300
log_error               = <%= @log_dir %>/mysql_error.log
log-slow-queries        = <%= @log_dir %>/mysql_slow_queries.log
long-query-time         = 1
old_passwords           = 1
!includedir <%= @config_dir %>

[mysqld_safe]
log-error               = <%= @log_dir %>/mysql_error.log
pid-file                = <%= @pid_dir %>/mysqld.pid
socket                  = <%= @pid_dir %>/mysqld.sock
```

ERROR MESSAGE:
```
==> d01: [2015-01-16T21:01:55+00:00] INFO: mysql_config[myappname] sending restart action to mysql_service[myappname] (delayed)
==> d01: [2015-01-16T21:01:57+00:00] INFO: service[myappname :restart stop mysql-myappname] stopped
==> d01: 
==> d01: ================================================================================
==> d01: Error executing action `start` on resource 'service[myappname :restart start mysql-myappname]'
==> d01: ================================================================================
==> d01: 
==> d01: 
==> d01: Mixlib::ShellOut::CommandTimeout
==> d01: --------------------------------
==> d01: Command timed out after 600s:
==> d01: 
==> d01: Command exceeded allowed execution time, process terminated
==> d01: 
==> d01: ---- Begin output of /sbin/start mysql-myappname ----
==> d01: 
==> d01: STDOUT: 
==> d01: 
==> d01: STDERR: 
==> d01: 
==> d01: ---- End output of /sbin/start mysql-myappname ----
==> d01: 
==> d01: Ran /sbin/start mysql-myappname returned 
==> d01: 
==> d01: 
==> d01: Resource Declaration:
==> d01: ---------------------
==> d01: # In /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_upstart.rb
==> d01: 
==> d01: 
==> d01: 
==> d01:  63:           service "#{new_resource.name} :restart start #{mysql_name}" do
==> d01: 
==> d01:  64:             service_name mysql_name
==> d01: 
==> d01:  65:             provider Chef::Provider::Service::Upstart
==> d01: 
==> d01:  66:             action :start
==> d01: 
==> d01:  67:           end
==> d01: 
==> d01:  68:         end
==> d01: 
==> d01: 
==> d01: 
==> d01: Compiled Resource:
==> d01: ------------------
==> d01: # Declared in /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_upstart.rb:63:in `block in <class:Upstart>'
==> d01: 
==> d01: service("myappname :restart start mysql-myappname") do
==> d01:   provider Chef::Provider::Service::Upstart
==> d01:   action [:start]
==> d01:   supports {:restart=>false, :reload=>false, :status=>false}
==> d01:   retries 0
==> d01:   retry_delay 2
==> d01:   default_guard_interpreter :default
==> d01:   service_name "mysql-myappname"
==> d01:   pattern "myappname :restart start mysql-myappname"
==> d01:   declared_type :service
==> d01:   cookbook_name "myappname"
==> d01: end
==> d01: 
==> d01: 
==> d01: [2015-01-16T21:13:01+00:00] INFO: Running queued delayed notifications before re-raising exception
==> d01: 
==> d01: ================================================================================
==> d01: Error executing action `restart` on resource 'mysql_service[myappname]'
==> d01: ================================================================================
==> d01: 
==> d01: 
==> d01: Mixlib::ShellOut::CommandTimeout
==> d01: --------------------------------
==> d01: service[myappname :restart start mysql-myappname] (/var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_upstart.rb line 63) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
==> d01: 
==> d01: Command exceeded allowed execution time, process terminated
==> d01: 
==> d01: ---- Begin output of /sbin/start mysql-myappname ----
==> d01: 
==> d01: STDOUT: 
==> d01: 
==> d01: STDERR: 
==> d01: 
==> d01: ---- End output of /sbin/start mysql-myappname ----
==> d01: 
==> d01: Ran /sbin/start mysql-myappname returned 
==> d01: 
==> d01: Resource Declaration:
==> d01: ---------------------
==> d01: # In /var/chef/cache/cookbooks/myappname/recipes/default.rb
==> d01: 
==> d01:  19: mysql_service "#{node[:app][:name]}" do
==> d01:  20:   version "5.6"
==> d01:  21:   initial_root_password "#{node[:app][:name]}123"
==> d01:  22:   action [:create, :start]
==> d01:  23: end
==> d01:  24: 
==> d01: 
==> d01: Compiled Resource:
==> d01: ------------------
==> d01: # Declared in /var/chef/cache/cookbooks/myappname/recipes/default.rb:19:in `from_file'
==> d01: 
==> d01: mysql_service("myappname") do
==> d01:   action [:create, :start]
==> d01:   updated true
==> d01:   updated_by_last_action true
==> d01:   retries 0
==> d01:   retry_delay 2
==> d01:   default_guard_interpreter :default
==> d01:   declared_type :mysql_service
==> d01:   cookbook_name "myappname"
==> d01:   recipe_name "default"
==> d01:   version "5.6"
==> d01:   initial_root_password "myappname123"
==> d01:   package_action :install
==> d01:   instance "myappname"
==> d01:   run_user "mysql"
==> d01:   run_group "mysql"
==> d01:   charset "utf8"
==> d01:   port "3306"
==> d01: end
==> d01: 
==> d01: [2015-01-16T21:13:01+00:00] ERROR: Running exception handlers
==> d01: [2015-01-16T21:13:01+00:00] ERROR: Exception handlers complete
==> d01: [2015-01-16T21:13:01+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> d01: [2015-01-16T21:13:01+00:00] INFO: Sending resource update report (run-id: 742659a0-d648-44fa-879f-a025745b3574)
==> d01: [2015-01-16T21:13:02+00:00] ERROR: mysql_service[myappname] (myappname::default line 19) had an error: Mixlib::ShellOut::CommandTimeout: service[myappname :restart start mysql-myappname] (/var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_upstart.rb line 63) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
==> d01: Command exceeded allowed execution time, process terminated
==> d01: ---- Begin output of /sbin/start mysql-myappname ----
==> d01: STDOUT: 
==> d01: STDERR: 
==> d01: ---- End output of /sbin/start mysql-myappname ----
==> d01: Ran /sbin/start mysql-myappname returned 
==> d01: [2015-01-16T21:13:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by someara** [comment]
The 'mysql_service[default]' resource's internal my.cnf (probably at
/etc/mysql-myappname/my.cnf) already contains lines for pid-file, socket,
and user... by re-specifying them in your site config, you're overriding
them and probably confusing the client.

Try ommiting anything you find in /etc/mysql-myappname/my.cnf from your
user supplied template

-s

**Comment by JAG-01** [comment]
That did it! Thanks! Here's my new template (omitting duplicates). Now I see how my template is called by "/etc/mysql-myappname/my.cnf" so I don't want to conflict. 

```
# Template file
# Generated by Chef for <%= node[:hostname] %>
# Controlling Cookbook: <%= @cookbook_name %>
#
# <%= @config_dir %>/<%= @app_name %>.cnf

[mysqld]
max_allowed_packet      = 10485760
max_connections         = 300
long-query-time         = 1
old_passwords           = 1
```

My apologies that this wasn't related to your patch, and many thanks again for the help!!

Might there be plans to give the "mysql" cookbook users access to these attributes (e.g. "log-error", "pid-file" etc.) found in the "/etc/mysql-myappname/my.cnf" file?

**Comment by someara** [comment]
I don't see why not (other than causing confusion around multiple
instances).
Can you open an issue so I can track it? I won't have time to get to it
tonight.

-s

**Comment by JAG-01** [comment]
Awesome, I have created https://github.com/chef-cookbooks/mysql/issues/281.
Much appreciated!
