### ISSUE TITLE
encoding failures (Encoding::InvalidByteSequenceError)

### ISSUE THREAD

**Issue by joshuacox** [chef-cookbooks/mysql#286]
Using this Dockerfile:

https://github.com/joshuacox/ddd

I get the following error:
```
/opt/chef/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
```
This appears to be maybe the same issue as seen here:
https://github.com/chef-cookbooks/mysql/issues/279

I have reproduced using both jessie and wheezy:

https://registry.hub.docker.com/u/joshuacox/docker-chef-solo/

```
Using openssl (2.0.2) from git://github.com/opscode-cookbooks/openssl.git (at master)                                                                                                                       [98/4239]
Using php (1.5.0) from git://github.com/opscode-cookbooks/php.git (at master)
Using pacman (1.1.1) from git://github.com/jesseadams/pacman.git (at master)
Installing rbac (1.0.2) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io/api/v1)
Using postgresql (3.4.14) from git://github.com/hw-cookbooks/postgresql.git (at master)
Installing smf (2.2.1) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io/api/v1)
Using vdd (0.0.0) from git://github.com/joshuacox/vdd-cookbook.git (at master)
Using vdd_example (0.0.0) from git://github.com/joshuacox/vdd_example-cookbook.git (at master)
Using windows (1.36.1) from git://github.com/opscode-cookbooks/windows.git (at master)
Using xfs (1.1.0) from git://github.com/opscode-cookbooks/xfs.git (at master)
Using xml (1.2.9) from git://github.com/opscode-cookbooks/xml.git (at master)
Installing yum (3.5.2) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io/api/v1)
Installing yum-epel (0.6.0) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io/api/v1)
Installing yum-mysql-community (0.1.11) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io/api/v1)
/opt/chef/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
        from /opt/chef/embedded/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
        from /opt/chef/embedded/lib/ruby/2.1.0/json/common.rb:155:in `new'
        from /opt/chef/embedded/lib/ruby/2.1.0/json/common.rb:155:in `parse'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:473:in `from_json'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook.rb:36:in `from_path'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.3/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:86:in `cookbook'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-3.2.3/lib/berkshelf/cookbook_store.rb:67:in `import
```

**Comment by someara** [comment]
that's really weird... I looks like its crashing after resolving yum-mysql-community, just like #279.

I did published a 0.1.12 version of that cookbook just in case there was some weird artifact corruption going on.

Can you try again and let me know if this persists?

-s

**Comment by joshuacox** [comment]
I do believe it picked up your 0.1.12 version, as seen below, but the problem indeed persists.  Though it only seems to persist in the docker environment, when I berks vendor locally on my debian jessie laptop everything appears fine.  There might be a version  mismatch in that case though, I'm going to update ruby etc here on this laptop to emulate the same conditions.

```
Installing yum-mysql-community (0.1.12) from https://api.berkshelf.com ([opscode] https://supermarket.chef.io/api/v1)
/opt/chef/embedded/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
```

**Comment by joshuacox** [comment]
I tracked it down to UTF-8 not actually being gen'd on the docker image yet.  I've updated my docker images accordingly, those interested can see the lines below.

```
RUN apt-get -y install locales
RUN echo 'en_US.UTF-8 UTF-8'>>/etc/locale.gen
RUN locale-gen
ENV LANG en_US.UTF-8
```

**Comment by someara** [comment]
Thanks for tracking this down!

**Comment by joshuacox** [comment]
I appreciate the quick response as well from you, hopefully @eriksenonline in https://github.com/chef-cookbooks/mysql/issues/279 has worked around his issue as well.
