### ISSUE TITLE
Vagrant/Ubuntu 14 Package error

### ISSUE THREAD

**Issue by bassrock** [chef-cookbooks/mysql#298]
I keep getting the following error on Vagrant using Ubuntu 14. Is this a known issue or something I am doing wrong? I am trying to setup the mysql replication and copied the necessary steps.

```
==> default: ================================================================================
==> default: Error executing action `install` on resource 'package[master :create mysql-server-5.6]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: STDOUT: 
==> default: STDERR: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
==> default: ---- End output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 returned 100
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service.rb
==> default: 
==> default:  30:         package "#{new_resource.name} :create #{server_package_name}" do
==> default:  31:           package_name server_package_name
==> default:  32:           version parsed_version if node['platform'] == 'smartos'
==> default:  33:           version new_resource.package_version
==> default:  34:           action new_resource.package_action
==> default:  35:         end
==> default:  36: 
==> default: 
==> default: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service.rb:30:in `block in <class:MysqlService>'
==> default: 
==> default: package("master :create mysql-server-5.6") do
==> default:   action [:install]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   package_name "mysql-server-5.6"
==> default:   version "5.6.19-0ubuntu0.14.04.1"
==> default:   cookbook_name :Symfony2
==> default: end
==> default: 
==> default: 
==> default: 
==> default: [2015-02-17T04:47:02+07:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: ================================================================================
==> default: Error executing action `create` on resource 'mysql_service[master]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: 
==> default: ------------------------------------
==> default: package[master :create mysql-server-5.6] (/tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service.rb line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: STDOUT: 
==> default: STDERR: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
==> default: ---- End output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 returned 100
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/Symfony2/recipes/mysql_replication.rb
==> default: 
==> default:  11: mysql_service 'master' do
==> default:  12:   port '3306'
==> default:  13:   version '5.6'
==> default:  14:   bind_address '0.0.0.0'
==> default:  15:   initial_root_password root_pass
==> default:  16:   action [:create, :start]
==> default:  17: end
==> default:  18: 
==> default: 
==> default: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/Symfony2/recipes/mysql_replication.rb:11:in `from_file'
==> default: 
==> default: mysql_service("master") do
==> default:   action [:create, :start]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   cookbook_name :Symfony2
==> default:   recipe_name "mysql_replication"
==> default:   port "3306"
==> default:   version "5.6"
==> default:   bind_address "0.0.0.0"
==> default:   initial_root_password "root"
==> default:   instance "master"
==> default:   package_action :install
==> default:   run_user "mysql"
==> default:   run_group "mysql"
==> default: end
==> default: 
==> default: 
==> default: 
==> default: [2015-02-17T04:47:02+07:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-02-17T04:47:02+07:00] ERROR: Running exception handlers
==> default: [2015-02-17T04:47:02+07:00] ERROR: Exception handlers complete
==> default: [2015-02-17T04:47:02+07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-02-17T04:47:02+07:00] ERROR: mysql_service[master] (Symfony2::mysql_replication line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: package[master :create mysql-server-5.6] (/tmp/vagrant-chef-3/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service.rb line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: STDOUT: 
==> default: STDERR: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
==> default: ---- End output of apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-server-5.6=5.6.19-0ubuntu0.14.04.1 returned 100
==> default: [2015-02-17T04:47:02+07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by someara** [comment]
You probably need to put 'apt::default' in your run_list.

If you're not driving Vagrant with test-kitchen, then you'll need to
replicate this in you Vagrantfile.
https://github.com/chef-cookbooks/mysql/blob/master/.kitchen.yml#L24

-s

**Comment by bassrock** [comment]
Yep apt is in my recipe/run list. It looks like the install is failing or getting interrupted somehow.

**Comment by bassrock** [comment]
Ok nvm. Turns out another package failed to install breaking apt.

**Comment by danielBingham** [comment]
@bassrock Can you give more details?  I'm running into this exact same issue over and have been unable to find a solution.  I'm just running through the LearnChef tutorials and I can't seem to get it to complete!

**Comment by bassrock** [comment]
@danielBingham Another one of my cookbooks ended up breaking apt-get which caused this one to fail.
