### ISSUE TITLE
Unable to use mysql_service

### ISSUE THREAD

**Issue by dullyouth** [chef-cookbooks/mysql#397]
Using Chef: 12.6.0 and  chef-mysql 6.1.2 on ubuntu 15.10
```
==> default: [2016-01-18T02:47:02+00:00] INFO: Processing mysql_service[instance-1] action create (mattr::database line 13)
==> default:
==> default: ================================================================================
==> default: Error executing action `create` on resource 'mysql_service[instance-1]'
==> default: ================================================================================
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `[]' for nil:NilClass
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default: /var/chef/cache/cookbooks/mysql/libraries/helpers.rb:380:in `package_name_for'
==> default: /var/chef/cache/cookbooks/mysql/libraries/helpers.rb:421:in `server_package'
==> default: /var/chef/cache/cookbooks/mysql/libraries/helpers.rb:432:in `server_package_name'
==> default: /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_base.rb:31:in `block in <class:MysqlServiceBase>'
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /var/chef/cache/cookbooks/mattr/recipes/database.rb
==> default:
==> default:  13: mysql_service 'instance-1' do
==> default:  14:   action [:create]
==> default:  15: end
==> default:  16:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /var/chef/cache/cookbooks/mattr/recipes/database.rb:13:in `from_file'
==> default:
==> default: mysql_service("instance-1") do
==> default:   action [:create]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   declared_type :mysql_service
==> default:   cookbook_name "mattr"
==> default:   recipe_name "database"
==> default: end
```

**Comment by dullyouth** [comment]
Just realized 15.10 isn't supported :sob:
