### ISSUE TITLE
ubuntu 16.04 -> mysql 5.7 -> error

### ISSUE THREAD

**Issue by aight8** [chef-cookbooks/mysql#436]
### Cookbook version
8.0.1

### Chef-client version
12

### Platform Details
ubuntu 16.04 xenial

### Output

```
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'mysql_service[default]'
==> default:     
==> default: ================================================================================
==> default:     
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     mysql_server_installation_package[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-server-5.7] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default:     ---- Begin output of apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 ----
==> default:     STDOUT: Reading package lists...
==> default:     Building dependency tree...
==> default:     Reading state information...
==> default:     STDERR: E: Version '5.7.12-0ubuntu1.1' for 'mysql-server-5.7' was not found
==> default:     ---- End output of apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 ----
==> default:     Ran apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 returned 100
==> default:     
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/blabla/recipes/db_mysql.rb
==> default:     
==> default:       5: mysql_service 'default' do
==> default:       6:   version '5.7'
==> default:       7:   bind_address '0.0.0.0'
==> default:       8:   port '3306'
==> default:       9:   data_dir '/data/mysql'
==> default:      10:   initial_root_password root_password
==> default:      11:   action [:create, :start]
==> default:      12: end
```

**Comment by ofir-petrushka** [comment]
On ubuntu 12.04

```
           ================================================================================
           Error executing action `create` on resource 'mysql_client_installation_package[default]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           apt_package[mysql-client-5.5] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
           ---- Begin output of apt-get -q -y install mysql-client-5.5=5.5.49-0ubuntu0.12.04.1 ----
           STDOUT: Reading package lists...
           Building dependency tree...
           Reading state information...
           STDERR: E: Version '5.5.49-0ubuntu0.12.04.1' for 'mysql-client-5.5' was not found
           ---- End output of apt-get -q -y install mysql-client-5.5=5.5.49-0ubuntu0.12.04.1 ----
           Ran apt-get -q -y install mysql-client-5.5=5.5.49-0ubuntu0.12.04.1 returned 100
```

**Comment by ofir-petrushka** [comment]
The new strict versioning would cause needed to update this recipe every php update?
Commit 824e854a1260c02800304a23c7d34efa8a627672
libraries/helpers.rb
```
+      return '5.5.49-0ubuntu0.12.04.1' if major_version == '5.5' && precise?
+      return '5.5.49-0ubuntu0.14.04.1' if major_version == '5.5' && trusty?
+      return '5.6.30-0ubuntu0.14.04.1' if major_version == '5.6' && trusty?
+      return '5.6.30-0ubuntu0.15.04.1' if major_version == '5.6' && vivid?
+      return '5.6.30-0ubuntu0.15.10.1' if major_version == '5.6' && wily?
+      return '5.7.12-0ubuntu1.1' if major_version == '5.7' && xenial?
```

**Comment by gaieges** [comment]
Came across the same problem.  Found that @ofir-petrushka 's fix (specifying blank version) works for me as well:

```
mysql_client 'default' do
  action :create
  package_version '' 
end
```
