### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by AneudyM** [chef-cookbooks/mysql#442]
### Cookbook version
`8.0.1`

### Chef-client version
`Chef Client, version 12.11.18`

### Platform Details
`Ubuntu 14.04.4 LTS trusty`

### Scenario:
I am trying to install a simple database server using the mysql chef cookbook.

### Steps to Reproduce:
I am using the cookbook to install a MySQL Database server on a Chef Node running Ubuntu 14.04 Trusty.

1. I downloaded the latest version of the **mysql cookbook (8.0.1)**, untared and moved the **'mysql/'** directory to the **'cookbooks/'** directory, and added the dependency to the cookbook **metadata.rb** file as follows:

   `depends 'mysql', '~> 8.0.1'`

2. Created a new recipe called **database.rb** and inserted the following  code:
    ```
    mysql_service 'default' do
        port '3306'
        version '5.5'
        initial_root_password 'djb5944014'
        action [ :create, :start ]
   end
```
3. Inserted the **database.rb** recipe into the default.rb recipe:

    `include_recipe 'icinga2-crossover::database'`

4. Uploaded the cookbook and its dependencies to the Chef Server:

    `$ knife cookbook upload icinga2-crossover --include-dependencies`

5. Added the cookbook to the run list of the Chef Node:

`$ knife node run_list add chef-node-one "recipe[icinga2-crossover]"`

6. Ran the Chef Client on the Chef Node:

    `$ sudo chef-client`

### Expected Result:
I am expecting that the MySQL Server gets installed after running the **chef-client** command on my chef node.

### Actual Result:
```
chefnode@chef-node:~$ sudo chef-client
Starting Chef Client, version 12.11.18
resolving cookbooks for run list: ["icinga2-crossover"]
Synchronizing Cookbooks:
  - icinga2-crossover (0.1.0)
  - mysql (8.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: icinga2-crossover::database
  * mysql_service[default] action create
    * mysql_server_installation_package[default] action install
      * apt_package[mysql-server-5.5] action install (up to date)
      * apt_package[perl-Sys-Hostname-Long] action nothing (skipped due to action :nothing)
      * execute[Initial DB setup script] action nothing (skipped due to action :nothing)
       (up to date)
    * mysql_service_manager_upstart[default] action create
      * group[mysql] action create (up to date)
      * user[mysql] action create (up to date)
      * service[mysql] action stop (up to date)
      * service[mysql] action disable (up to date)
      * file[/etc/mysql/my.cnf] action delete (up to date)
      * file[/etc/my.cnf] action delete (up to date)
      * link[/usr/share/my-default.cnf] action create (skipped due to not_if)
      * directory[/etc/mysql-default] action create (up to date)
      * directory[/etc/mysql-default/conf.d] action create (up to date)
      * directory[/run/mysql-default] action create (up to date)
      * directory[/var/log/mysql-default] action create (up to date)
      * directory[/var/lib/mysql-default] action create (up to date)
      * template[/etc/mysql-default/my.cnf] action create (up to date)
      * bash[default initial records] action run
        - execute "bash"  "/tmp/chef-script20160728-17026-nl1xuf"
      * apt_package[apparmor] action install (up to date)
      * directory[/etc/apparmor.d/local/mysql] action create (up to date)
      * template[/etc/apparmor.d/local/usr.sbin.mysqld] action create (up to date)
      * template[/etc/apparmor.d/usr.sbin.mysqld] action create (up to date)
      * template[/etc/apparmor.d/local/mysql/default] action create (up to date)
      * service[default apparmor] action nothing (skipped due to action :nothing)
    
  
  * mysql_service[default] action start
    * mysql_service_manager_upstart[default] action start
      * template[/usr/sbin/mysql-default-wait-ready] action create (up to date)
      * template[/etc/init/mysql-default.conf] action create (up to date)
      * service[mysql-default] action start
        
        ================================================================================
        Error executing action `start` on resource 'service[mysql-default]'
        ================================================================================
        
        NoMethodError
        -------------
        undefined method `[]' for nil:NilClass
        
        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_upstart.rb
        
         42:       service mysql_name do
         43:         provider Chef::Provider::Service::Upstart
         44:         supports status: true
         45:         action [:start]
         46:       end
         47:     end
        
        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_upstart.rb:42:in `block in <class:MysqlServiceManagerUpstart>'
        
        service("mysql-default") do
          provider Chef::Provider::Service::Upstart
          action [:start]
          supports {:status=>true}
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          service_name "mysql-default"
          pattern "mysql-default"
          declared_type :service
          cookbook_name "icinga2-crossover"
        end
        
        Platform:
        ---------
        x86_64-linux
        
      
      ================================================================================
      Error executing action `start` on resource 'mysql_service_manager_upstart[default]'
      ================================================================================
      
      NoMethodError
      -------------
      service[mysql-default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_upstart.rb line 42) had an error: NoMethodError: undefined method `[]' for nil:NilClass
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb
      
       50:           svc = mysql_service_manager(name, &block)
       51:         when 'sysvinit'
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb:50:in `svc_manager'
      
      mysql_service_manager_upstart("default") do
        action [:start]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :mysql_service_manager
        cookbook_name "icinga2-crossover"
        version "5.5"
        initial_root_password "djb5944014"
        port "3306"
        instance "default"
        run_user "mysql"
        run_group "mysql"
        socket "/run/mysql-default/mysqld.sock"
      end
      
      Platform:
      ---------
      x86_64-linux
      
    
    ================================================================================
    Error executing action `start` on resource 'mysql_service[default]'
    ================================================================================
    
    NoMethodError
    -------------
    mysql_service_manager_upstart[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 50) had an error: NoMethodError: service[mysql-default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_upstart.rb line 42) had an error: NoMethodError: undefined method `[]' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icinga2-crossover/recipes/database.rb
    
      7: mysql_service 'default' do
      8: 	port '3306'
      9: 	version '5.5'
     10: 	initial_root_password 'djb5944014'
     11: 	action [ :create, :start ]
     12: end
     13: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icinga2-crossover/recipes/database.rb:7:in `from_file'
    
    mysql_service("default") do
      action [:create, :start]
      updated true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :mysql_service
      cookbook_name "icinga2-crossover"
      recipe_name "database"
      port "3306"
      version "5.5"
      initial_root_password "djb5944014"
      install_method "auto"
      service_manager "auto"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2016-07-28T23:43:58-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-28T23:43:58-04:00] ERROR: Exception handlers complete
Chef Client failed. 3 resources updated in 04 seconds
[2016-07-28T23:43:58-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-28T23:43:58-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-28T23:43:58-04:00] ERROR: mysql_service[default] (icinga2-crossover::database line 7) had an error: NoMethodError: mysql_service_manager_upstart[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 50) had an error: NoMethodError: service[mysql-default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service_manager_upstart.rb line 42) had an error: NoMethodError: undefined method `[]' for nil:NilClass
[2016-07-28T23:43:58-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jsw2** [comment]
Resolved?

**Comment by salsa-dev** [comment]
So how this issue was actually resolved?

**Comment by grrava** [comment]
I'd like to know as well...

**Comment by corporealfunk** [comment]
I'm seeing this exact problem now after a week of successfully using this cookbook. The problem doesn't happen on the first chef run, only on subsequent runs.

**Comment by RyanJarv** [comment]
This is an issue with the Upstart provider when the service is not in a start or stop state or when the output of /bin/status <job> doesn't match this regex https://github.com/chef/chef/blob/9d09f9e23db45eaf71bc9421507a25fccac1293b/lib/chef/provider/service/upstart.rb#L36

Also I think there is another issue here with the Mysql upstart config, it times out in the post-start section regardless of whether Mysqld is trying to start or erred out immediately. In the case you run chef it hangs on waiting for mysql to come up (although it never will) then when you Ctl-C or the resource times it seems the upstart wait script continues to run, at this point when you rerun chef the state is in post-start which then triggers the bug in the upstart provider.

**Comment by RyanJarv** [comment]
Opened a ticket for the upstart issue.
 https://github.com/chef/chef/issues/5513
