### ISSUE TITLE
CentOS 7.2.1511, MySQL Server 5.6 > No candidate version available for mysql-community-server

### ISSUE THREAD

**Issue by ericleestewart** [chef-cookbooks/mysql#443]
### Cookbook version
8.0.1

### Chef-client version
Chef: 12.10.24

### Platform Details
CentOS Linux release 7.2.1511 (Core)

### Scenario:
Attempt to install MySQL Server using Chef Client and Vagrant.

### Steps to Reproduce:
* Include depends in metadata.rb
```
depends           'mysql'
```

* Import cookbooks.
```
berks install
```

* Add mysql_service setup block to main recipe.
```
mysql_service 'default' do
  charset 'utf8'
  port '3306'
  version '5.6'
  initial_root_password 'xxxxxx'
  action [:create, :start]
end
```

* Run vagrant up
```
vagrant up
```

### Expected Result:
Install should complete successfully and mysql server show be running.

### Actual Result:
```
* No candidate version available for mysql-community-server

================================================================================
Error executing action `install` on resource 'yum_package[mysql-community-server]'
================================================================================

Chef::Exceptions::Package
-------------------------
No candidate version available for mysql-community-server

Cookbook Trace:
---------------
/tmp/vagrant-chef/444d40d47d2e3b137eabc15960affef9/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
/tmp/vagrant-chef/444d40d47d2e3b137eabc15960affef9/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
/tmp/vagrant-chef/444d40d47d2e3b137eabc15960affef9/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

Resource Declaration:
---------------------
# In /tmp/vagrant-chef/444d40d47d2e3b137eabc15960affef9/cookbooks/mysql/libraries/mysql_server_installation_package.rb

 17:       package package_name do
 18:         version package_version if package_version
 19:         options package_options if package_options
 20:         notifies :install, 'package[perl-Sys-Hostname-Long]', :immediately if platform_family?('suse')
 21:         notifies :run, 'execute[Initial DB setup script]', :immediately if platform_family?('suse')
 22:         action :install
 23:       end
 24: 

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef/444d40d47d2e3b137eabc15960affef9/cookbooks/mysql/libraries/mysql_server_installation_package.rb:17:in `block in <class:MysqlServerInstallationPackage>'

yum_package("mysql-community-server") do
  package_name "mysql-community-server"
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :package
  cookbook_name :"stack-builder"
  flush_cache {:before=>false, :after=>false}
  version "5.6.29-2.el7"
end

Platform:
---------
x86_64-linux
```

Additional Notes:
-----------------
After running yum search mysql, it turns out that no version of mysql-community-server is even available:
```
[vagrant@localhost ~]$ yum search mysql
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.chi.host-engine.com
 * epel: mirror.symnds.com
 * extras: centos.unixheads.org
 * updates: centos.hostingxtreme.com
 * webtatic: us-east.repo.webtatic.com
================================================================================ N/S matched: mysql =================================================================================
MySQL-python.x86_64 : An interface to MySQL
MySQL-zrm.noarch : MySQL backup manager
akonadi-mysql.x86_64 : Akonadi MySQL backend support
apr-util-mysql.x86_64 : APR utility library MySQL DBD driver
collectd-mysql.x86_64 : MySQL plugin for collectd
dmlite-plugins-mysql.x86_64 : MySQL plugin for dmlite
dovecot-mysql.x86_64 : MySQL back end for dovecot
dpm-copy-server-mysql.x86_64 : DPM copy server with MySQL database back-end
dpm-name-server-mysql.x86_64 : DPM name server with MySQL database back-end
dpm-server-mysql.x86_64 : Disk Pool Manager (DPM) server with MySQL database back-end
dpm-srm-server-mysql.x86_64 : DPM SRM server with MySQL database back-end
dspam-mysql.x86_64 : MySQL storage driver for libdspam
exim-mysql.x86_64 : MySQL lookup support for Exim
freeradius-mysql.x86_64 : MySQL support for freeradius
fts-mysql.x86_64 : File Transfer Service V3 mysql plug-in
gnokii-smsd-mysql.x86_64 : MySQL support for Gnokii SMS daemon
holland-mysqldump.noarch : Logical mysqldump backup plugin for Holland
holland-mysqllvm.noarch : Holland LVM snapshot backup plugin for MySQL
lfc-server-mysql.x86_64 : LCG File Catalog (LFC) server with MySQL database back-end
libdbi-dbd-mysql.x86_64 : MySQL plugin for libdbi
libgda-mysql.x86_64 : Mysql provider for libgda
libnss-mysql.x86_64 : NSS library for MySQL
libodb-mysql.x86_64 : MySQL ODB runtime library from Code Synthesis
libodb-mysql-devel.x86_64 : Development files for libodb-mysql
lighttpd-mod_mysql_vhost.x86_64 : Virtual host module for lighttpd that uses a MySQL database
mysql++.x86_64 : C++ wrapper for the MySQL C API
mysql++-devel.x86_64 : MySQL++ developer files (headers, examples, etc.)
mysql++-manuals.x86_64 : MySQL++ user and reference manuals
mysql-connector-java.noarch : Official JDBC driver for MySQL
mysql-connector-odbc.x86_64 : ODBC driver for MySQL
mysql-connector-python.noarch : MySQL Connector for Python 2
mysql-mmm.noarch : Multi-Master Replication Manager for MySQL
mysql-proxy.x86_64 : A proxy for the MySQL Client/Server protocol
mysql-proxy-devel.x86_64 : Development files for mysql-proxy
mysql-utilities.noarch : MySQL Utilities
mysqlreport.noarch : A friendly report of important MySQL status values
mysqltuner.noarch : MySQL configuration assistant
nagios-plugins-mysql.x86_64 : Nagios Plugin - check_mysql
nodejs-mysql.noarch : A node.js driver for mysql
opendbx-mysql.x86_64 : MySQL backend - provides mysql support in opendbx
opensips-mysql.x86_64 : MySQL storage support for the OpenSIPS
owncloud-mysql.noarch : MySQL database support for ownCloud
pcp-pmda-mysql.x86_64 : Performance Co-Pilot (PCP) metrics for MySQL
pdns-backend-mysql.x86_64 : MySQL backend for pdns
perdition-mysql.x86_64 : Library to allow perdition to access MySQL based pop maps
perl-DBD-MySQL.x86_64 : A MySQL interface for Perl
perl-DateTime-Format-MySQL.noarch : Parse and format MySQL dates and times
perl-Test-mysqld.noarch : Mysqld runner for tests
php-ZendFramework-Db-Adapter-Mysqli.noarch : Zend Framework database adapter for mysqli
php-ZendFramework-Db-Adapter-Pdo-Mysql.noarch : Zend Framework database adapter for MySQL PDO
php-mysql.x86_64 : A module for PHP applications that use MySQL databases
php-mysqlnd.x86_64 : A module for PHP applications that use MySQL databases
php-pear-MDB2-Driver-mysql.noarch : MySQL MDB2 driver
php-pear-MDB2-Driver-mysqli.noarch : MySQL Improved MDB2 driver
php54w-mysql.x86_64 : A module for PHP applications that use MySQL databases
php54w-mysqlnd.x86_64 : A module for PHP applications that use MySQL databases
php55w-mysql.x86_64 : A module for PHP applications that use MySQL databases
php55w-mysqlnd.x86_64 : A module for PHP applications that use MySQL databases
php56w-mysql.x86_64 : A module for PHP applications that use MySQL databases
php56w-mysqlnd.x86_64 : A module for PHP applications that use MySQL databases
php70w-mysql.x86_64 : A module for PHP applications that use MySQL databases
php70w-mysqlnd.x86_64 : A module for PHP applications that use MySQL databases
poco-mysql.x86_64 : The Data/MySQL POCO component
proftpd-mysql.x86_64 : Module to add MySQL support to the ProFTPD FTP server
qt-mysql.i686 : MySQL driver for Qt's SQL classes
qt-mysql.x86_64 : MySQL driver for Qt's SQL classes
qt3-MySQL.i686 : MySQL drivers for Qt 3's SQL classes
qt3-MySQL.x86_64 : MySQL drivers for Qt 3's SQL classes
qt5-qtbase-mysql.x86_64 : MySQL driver for Qt5's SQL classes
redland-mysql.x86_64 : MySQL storage support for Redland
root-sql-mysql.x86_64 : MySQL client plugin for ROOT
rsyslog-mysql.x86_64 : MySQL support for rsyslog
soci-mysql.x86_64 : MySQL back-end for soci
soci-mysql-devel.x86_64 : MySQL back-end for soci
tcl-mysqltcl.x86_64 : MySQL interface for Tcl
voms-mysql-plugin.x86_64 : VOMS server plugin for MySQL
zabbix20-proxy-mysql.x86_64 : Zabbix proxy compiled to use MySQL
zabbix20-server-mysql.x86_64 : Zabbix server compiled to use MySQL
zabbix20-web-mysql.noarch : Zabbix web frontend for MySQL
zabbix22-proxy-mysql.x86_64 : Zabbix proxy compiled to use MySQL
zabbix22-server-mysql.x86_64 : Zabbix server compiled to use MySQL
zabbix22-web-mysql.noarch : Zabbix web frontend for MySQL
calligra-kexi-driver-mysql.x86_64 : Mysqwl driver for kexi
innotop.noarch : A MySQL and InnoDB monitor program
mariadb.x86_64 : A community developed branch of MySQL
mariadb-devel.i686 : Files for development of MariaDB/MySQL applications
mariadb-devel.x86_64 : Files for development of MariaDB/MySQL applications
mariadb-libs.i686 : The shared libraries required for MariaDB/MySQL clients
mariadb-libs.x86_64 : The shared libraries required for MariaDB/MySQL clients
mylvmbackup.noarch : Utility for creating MySQL backups via LVM snapshots
mysql-mmm-agent.noarch : MMM Database Server Agent Daemon and Libraries
mysql-mmm-monitor.noarch : MMM Monitor Server Daemon and Libraries
mysql-mmm-tools.noarch : MMM Control Scripts and Libraries
mytop.noarch : A top clone for MySQL
percona-xtrabackup.x86_64 : Online backup for InnoDB/XtraDB in MySQL, Percona Server and MariaDB
php-udan11-sql-parser.noarch : A validating SQL lexer and parser with a focus on MySQL dialect
phpMyAdmin.noarch : Handle the administration of MySQL over the World Wide Web
zabbix22-dbfiles-mysql.noarch : Zabbix database schemas, images, data and patches

  Name and summary matches only, use "search all" for everything.

```

**Comment by someara** [comment]
Fixed up in 8.0.2

**Comment by LukeEchobox** [comment]
@someara  

> Fixed up in 8.0.2 ? 

I'm still facing this problem with 8.0.2, is there a workaround to specify is specific version?

**Comment by LMtx** [comment]
The same problem - mysql version 8.0.4.

**Comment by LMtx** [comment]
@someara , @LukeEchobox one more info - for whatever reason to make this work you need to use this version of cookbook:
`cookbook 'mysql', '= 6.1.3'`

**Comment by LukeEchobox** [comment]
@LMtx  thanks :)

**Comment by hlarsen** [comment]
still seeing this issue with 8.2.0; works when specifying 6.1.3 as described previously.

thoughts?

**Comment by mastermindg** [comment]
On cookbook version 8.0.4. Centos 7.1. Package install is failing because Chef keeps on trying to install 5.6.29 and yum is forcing 5.6.35 for mysql-devel. Is there any way to force the sub-version to prevent the error/failure?

**Comment by hlarsen** [comment]
it's been a while so i can't remember if i pinpointed where the problem was in the mysql cookbook, however i ended up using the yum-mysql-community cookbook to add the repo for the version i needed.

**Comment by mastermindg** [comment]
I'm also using yum-mysql-community but all it's doing is adding the repo. The issue that I'm seeing is with the sub-version.

**Comment by pjohnson-ptc** [comment]
This issue should **not have** been closed.  

When dowloading and installing mysql-8.2.0 cookbook and running the cookbook with the following:

mysql_service 'default' do
   port '3306'
   version '5.7'
   initial_root_password '******'
   action [:create, :start]
end


**I get the following:**
[2017-01-18T09:18:29-06:00] ERROR: mysql_service[default] (cccs::default line 10) had an error: Chef::Exceptions::Package: mysql_server_installation_package[default] (/root/scm/chef-repo/.chef/local-mode-cache/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Chef::Exceptions::Package: yum_package[mysql-community-server] (/root/scm/chef-repo/.chef/local-mode-cache/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server
[2017-01-18T09:18:31-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by hlarsen** [comment]
@pjohnson-ptc per the readme you'll need to add the repo for the version you want - simplest is to use the yum-mysql-community cookbook and include the recipe for the mysql version you want.

**Comment by pjohnson-ptc** [comment]
@hlarsen  - OK, I think that makes sense.  I'll give it a try.
