### ISSUE TITLE
Error NoSuchResourceType on Amazon Linux 2016.03

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [chef-cookbooks/mysql#464]
### Cookbook version

8.0.0 - 8.0.2
Tested on 7.2.0 is not affected
### Chef-client version

Chef 12.13.37
### Platform Details

AWS Amazon Linux 2016.03
### Scenario:

Install and configure mysql
### Steps to Reproduce:

``` ruby
include_recipe 'yum-mysql-community::mysql56'

mysql_service 'name' do
  version '5.6'
  bind_address '127.0.0.1'
  port '3306'
  data_dir '/data'
  initial_root_password node['mysql']['server_root_password']
  action [:create, :start]
end

mysql2_chef_gem 'default' do
  action :install
end
```
### Expected Result:

MySql installed and configured
### Actual Result:

```
================================================================================
Error executing action `create` on resource 'mysql_service[name]'
================================================================================

Chef::Exceptions::NoSuchResourceType
------------------------------------
Cannot find a resource for mysql_service_manager on amazon version 2016.03

Cookbook Trace:
---------------
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/mysql/libraries/mysql_service.rb:50:in `svc_manager'
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/mysql/libraries/mysql_service.rb:72:in `block in <class:MysqlService>'
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------
# In /var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb

3: mysql_service 'ntc' do
4:   version '5.6'
5:   bind_address '127.0.0.1'
6:   port '3306'
7:   data_dir '/data'
8:   initial_root_password node['mysql']['server_root_password']
9:   action [:create, :start]
10: end
11: 

Compiled Resource:
------------------
# Declared in /var/chef/runs/d2a71799-81b4-49f5-ae42-0bf74ef147b9/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:3:in `from_file'

ysql_service("ntc") do
action [:create, :start]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :mysql_service
cookbook_name "my-cookbook"
recipe_name "setup_db"
version "5.6"
bind_address "127.0.0.1"
port "3306"
data_dir "/data"
initial_root_password "PASSWORD"
install_method "auto"
service_manager "auto"
end
```
### Update:

Having still little knowledge of Chef i tried to force the **provider** but the results where not so good

```
Recipe Compile Error in /var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb
================================================================================

NameError
---------
uninitialized constant Chef::Provider::MysqlServiceSystemd

Cookbook Trace:
---------------
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:7:in `block in from_file'
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:1:in `from_file'
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'

Relevant File Content:
----------------------
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:

1:  mysql_service 'my-cookbook' do
2:    version '5.7'
3:    bind_address '127.0.0.1'
4:    port '3306'
5:    data_dir '/data'
6:    initial_root_password node['mysql']['server_root_password']
7>>   provider Chef::Provider::MysqlServiceSystemd
8:    action [:create, :start]
9:  end
10:  
11:  mysql2_chef_gem 'default' do
12:    action :install
13:  end
14:  
```

**Comment by SharpEdgeMarshall** [comment]
Sorry duplicate of #438 but maybe mine is more detailed.

**Comment by SharpEdgeMarshall** [comment]
###Update:
Having still little knowledge of Chef i tried to force the **provider** but the result where not so good
```
Recipe Compile Error in /var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb
================================================================================
 
NameError
---------
uninitialized constant Chef::Provider::MysqlServiceSystemd
 
Cookbook Trace:
---------------
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:7:in `block in from_file'
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:1:in `from_file'
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
 
Relevant File Content:
----------------------
/var/chef/runs/5218be2f-6242-483a-9115-9ef9f7db53bf/local-mode-cache/cache/cookbooks/my-cookbook/recipes/setup_db.rb:
 
1:  mysql_service 'my-cookbook' do
2:    version '5.7'
3:    bind_address '127.0.0.1'
4:    port '3306'
5:    data_dir '/data'
6:    initial_root_password node['mysql']['server_root_password']
7>>   provider Chef::Provider::MysqlServiceSystemd
8:    action [:create, :start]
9:  end
10:  
11:  mysql2_chef_gem 'default' do
12:    action :install
13:  end
14:  
```

**Comment by cheeseplus** [comment]
As noted in #438 you may be able to set the service_manager manually to the correct init system for Amazon Linux. Closing as dupe but discussion can continue in #438.
