### ISSUE TITLE
Cookbook version from 7.2-8.3 doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by ashutoshvct** [chef-cookbooks/mysql#524]
### Cookbook version
7.2-8.3

### Chef-client version
12.19.36

### Platform Details
ubuntu 16.04 (local environment)

### Scenario:
I'm just trying to set the password for mysql root user

### Steps to Reproduce:
Try installing it with mysql version 5.7 on Ubuntu 16.04. Just install mysql and change the root password.

### Expected Result:
mysql must be installed and I must be able to login into it via root user and password.

### Actual Result:
It gives me this error:

  
      ================================================================================
      Error executing action `start` on resource 'service[mysqldefault :start mysql-mysqldefault]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /bin/systemctl --system start mysql-mysqldefault ----
      STDOUT: 
      STDERR: Job for mysql-mysqldefault.service failed because the control process exited with error code. See "systemctl status mysql-mysqldefault.service" and "journalctl -xe" for details.
      ---- End output of /bin/systemctl --system start mysql-mysqldefault ----
      Ran /bin/systemctl --system start mysql-mysqldefault returned 1
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb
      
       75:         service "#{new_resource.name} :start #{mysql_name}" do
       76:           service_name mysql_name
       77:           provider Chef::Provider::Service::Systemd
       78:           supports restart: true, status: true
       79:           action [:enable, :start]
       80:         end
       81:       end
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb:75:in `block in <class:MysqlServiceSystemd>'
      
      service("mysqldefault :start mysql-mysqldefault") do
        provider Chef::Provider::Service::Systemd
        action [:enable, :start]
        supports {:restart=>true, :status=>true}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "mysql-mysqldefault"
        enabled true
        running false
        masked false
        pattern "mysqldefault :start mysql-mysqldefault"
        declared_type :service
        cookbook_name "lamp-stack"
      end
      
      Platform:
      ---------
      x86_64-linux
      
[2017-05-10T15:28:10+05:30] INFO: Running queued delayed notifications before re-raising exception
    
    ================================================================================
    Error executing action `start` on resource 'mysql_service[mysqldefault]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    service[mysqldefault :start mysql-mysqldefault] (/var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb line 75) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl --system start mysql-mysqldefault ----
    STDOUT: 
    STDERR: Job for mysql-mysqldefault.service failed because the control process exited with error code. See "systemctl status mysql-mysqldefault.service" and "journalctl -xe" for details.
    ---- End output of /bin/systemctl --system start mysql-mysqldefault ----
    Ran /bin/systemctl --system start mysql-mysqldefault returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/lamp-stack/recipes/mysql.rb
    
      3: mysql_service "mysqldefault" do
      4:   initial_root_password mysqlpass["password"]
      5:   action [:create, :start]
      6: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/lamp-stack/recipes/mysql.rb:3:in `from_file'
    
    mysql_service("mysqldefault") do
      action [:create, :start]
      updated true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :mysql_service
      cookbook_name "lamp-stack"
      recipe_name "mysql"
      initial_root_password "xxxxxxxxxx"
      instance "mysqldefault"
      run_user "mysql"
      run_group "mysql"
      charset "utf8"
      port "3306"
      mysqld_options {}
    end
    
    Platform:
    ---------
    x86_64-linux
    
[2017-05-10T15:28:10+05:30] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-05-10T15:28:10+05:30] ERROR: Running exception handlers
Running handlers complete
[2017-05-10T15:28:10+05:30] ERROR: Exception handlers complete
Chef Client failed. 4 resources updated in 05 seconds
[2017-05-10T15:28:10+05:30] INFO: Sending resource update report (run-id: c0c25e36-603c-4b0d-bea3-bb829e10232b)
[2017-05-10T15:28:11+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-05-10T15:28:11+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-10T15:28:11+05:30] ERROR: mysql_service[mysqldefault] (lamp-stack::mysql line 3) had an error: Mixlib::ShellOut::ShellCommandFailed: service[mysqldefault :start mysql-mysqldefault] (/var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_systemd.rb line 75) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl --system start mysql-mysqldefault ----
STDOUT: 
STDERR: Job for mysql-mysqldefault.service failed because the control process exited with error code. See "systemctl status mysql-mysqldefault.service" and "journalctl -xe" for details.
---- End output of /bin/systemctl --system start mysql-mysqldefault ----
Ran /bin/systemctl --system start mysql-mysqldefault returned 1
[2017-05-10T15:28:11+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by ashutoshvct** [comment]
It was the Ubuntu update server issue. After fixing that and updating ubuntu, it works like a charm.
