### ISSUE TITLE
Cannot Access Variables in Template File of mysql_config Resource

### ISSUE THREAD

**Issue by enummela** [chef-cookbooks/mysql#527]
### Cookbook version
8.4.0

### Chef-client version
12.19.36

### Platform Details
Ubuntu 14.04

### Scenario:
Issue accessing parameters within template resource created through mysql_config wrapper resource.

### Steps to Reproduce:

**foo-mysql.rb**

```
# install MySQL server
mysql_service 'foo' do
  port '3306'
  version '5.6'
  initial_root_password 'root_pw'
  action [:create, :start]
end

mysql_config 'security_settings' do
  config_name 'security'
  instance 'foo'
  source 'security.cnf.erb'
  variables(
    :bind_address => '0.0.0.0'
  )
  action :create
  notifies :restart, "mysql_service[foo]"
end
```

**security.cnf.erb**
```
bind-address = <%= @params[:bind_address] %>
```

### Expected Result:
Successfully create MySQL config file with below contents

```
bind-address = 0.0.0.0
```

### Actual Result:

`@params` variable within template has value of nil. Is this not the correct way to access variables passed into the mysql_config template? If so then perhaps the documentation could be updated to reflect this?

```
* template[/etc/mysql-foo/conf.d/security.cnf] action create
             
             ================================================================================
             Error executing action `create` on resource 'template[/etc/mysql-foo/conf.d/security.cnf]'
             ================================================================================
             
             Chef::Mixin::Template::TemplateError
             ------------------------------------
             undefined method `[]' for nil:NilClass
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_config.rb
             
       39:       template "#{include_dir}/#{config_name}.cnf" do
       40:         owner new_resource.owner
       41:         group new_resource.group
       42:         mode '0640'
       43:         variables(new_resource.variables)
       44:         source new_resource.source
       45:         cookbook new_resource.cookbook
       46:         action :create
       47:       end
       48:     end
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_config.rb:39:in `block in <class:MysqlConfig>'
             
             template("/etc/mysql-foo/conf.d/security.cnf") do
        action [:create]
        default_guard_interpreter :default
        source "security.cnf.erb"
        variables {:bind_address=>"0.0.0.0"}
        declared_type :template
        cookbook_name "foo-mysql"
        mode "0640"
        owner "mysql"
        group "mysql"
        path "/etc/mysql-foo/conf.d/security.cnf"
        verifications []
             end
             
             Template Context:
             -----------------
             on line #3
        1: #
        2: # Override default bind address service listens on
        3: bind-address = <%= @params[:bind_address] %>
             
             System Info:
             ------------
             chef_version=13.1.31
             platform=ubuntu
             platform_version=14.04
             ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
             program_name=chef-client worker: ppid=1990;start=17:27:25;
             executable=/opt/chef/bin/chef-client
             
           
           ================================================================================
           Error executing action `create` on resource 'mysql_config[security_settings]'
           ================================================================================
           
           Chef::Mixin::Template::TemplateError
           ------------------------------------
           undefined method `[]' for nil:NilClass
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/foo-mysql/recipes/default.rb
           
            31: mysql_config 'security_settings' do
            32:   config_name 'security'
            33:   instance node['foo-mysql']['service_name']
            34:   source 'security.cnf.erb'
            35:   variables(
            36:     :bind_address => '0.0.0.0'
            37:   )
            38:   action :create
            39:   notifies :restart, "mysql_service[#{node['foo-mysql']['service_name']}]"
            40: end
            41: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/foo-mysql/recipes/default.rb:31:in `from_file'
           
           mysql_config("security_settings") do
             action [:create]
             default_guard_interpreter :default
             declared_type :mysql_config
             cookbook_name "foo-mysql"
             recipe_name "default"
             config_name "security"
             instance "foo"
             source "security.cnf.erb"
             variables {:bind_address=>"0.0.0.0"}
             include_dir "/etc/mysql-foo/conf.d"
           end
           
           Template Context:
           -----------------
           on line #3
             1: #
             2: # Override default bind address service listens on
             3: bind-address = <%= @params[:bind_address] %>
           
           System Info:
           ------------
           chef_version=13.1.31
           platform=ubuntu
           platform_version=14.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1990;start=17:27:25;
           executable=/opt/chef/bin/chef-client
           
       
       Running handlers:
       [2017-06-26T17:28:32+00:00] ERROR: Running exception handlers
       [2017-06-26T17:28:32+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-06-26T17:28:32+00:00] ERROR: Exception handlers complete
       [2017-06-26T17:28:32+00:00] ERROR: Exception handlers complete
       Chef Client failed. 41 resources updated in 01 minutes 07 seconds
       [2017-06-26T17:28:32+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-06-26T17:28:32+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-06-26T17:28:32+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-06-26T17:28:32+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-06-26T17:28:32+00:00] ERROR: 
       
       Chef::Mixin::Template::TemplateError (undefined method `[]' for nil:NilClass) on line #3:
       
         1: #
         2: # Override default bind address service listens on
         3: bind-address = <%= @params[:bind_address] %>
       
         (erubis):3:in `block in evaluate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/mixin/template.rb:161:in `_render_template'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/mixin/template.rb:147:in `render_template'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/template/content.rb:76:in `file_for_provider'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/file.rb:450:in `tempfile'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/file.rb:327:in `do_generate_content'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/file.rb:140:in `action_create'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider.rb:171:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource.rb:591:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:70:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block (2 levels) in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `each'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:97:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider.rb:212:in `compile_and_converge_action'
         (eval):2:in `action_create'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider.rb:171:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource.rb:591:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:70:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block (2 levels) in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `each'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:97:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:715:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:710:in `catch'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:710:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:749:in `converge_and_save'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:286:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:291:in `block in fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:244:in `block in run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:232:in `run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `loop'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:434:in `run_application'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:59:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/bin/chef-client:26:in `<top (required)>'
         /opt/chef/bin/chef-client:58:in `load'
         /opt/chef/bin/chef-client:58:in `<main>'
       
       
       [2017-06-26T17:28:32+00:00] ERROR: 
       
       Chef::Mixin::Template::TemplateError (undefined method `[]' for nil:NilClass) on line #3:
       
         1: #
         2: # Override default bind address service listens on
         3: bind-address = <%= @params[:bind_address] %>
       
         (erubis):3:in `block in evaluate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/mixin/template.rb:161:in `_render_template'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/mixin/template.rb:147:in `render_template'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/template/content.rb:76:in `file_for_provider'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/file.rb:450:in `tempfile'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/file.rb:327:in `do_generate_content'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider/file.rb:140:in `action_create'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider.rb:171:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource.rb:591:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:70:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block (2 levels) in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `each'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:97:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider.rb:212:in `compile_and_converge_action'
         (eval):2:in `action_create'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/provider.rb:171:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource.rb:591:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:70:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block (2 levels) in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `each'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:98:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/runner.rb:97:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:715:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:710:in `catch'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:710:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:749:in `converge_and_save'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:286:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:291:in `block in fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:244:in `block in run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:232:in `run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `loop'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:434:in `run_application'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:59:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/bin/chef-client:26:in `<top (required)>'
         /opt/chef/bin/chef-client:58:in `load'
         /opt/chef/bin/chef-client:58:in `<main>'
       
       
       [2017-06-26T17:28:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-06-26T17:28:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by enummela** [comment]
Resolved this through bypassing the `@params` variable and accessing the variables directly

```
bind-address = <%= @bind_address %>
```
